# Generated by Django 5.0.3 on 2024-04-05 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT')], max_length=20),
        ),
    ]
