# Generated by Django 5.0.3 on 2024-04-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_datetime_alter_order_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
