# Generated by Django 5.0.3 on 2024-04-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='order_time',
        ),
    ]
